services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    ports:
      - "3000:3000"
    volumes:
      - ./wa-session:/app/wa-session
      - ./contact.json:/app/contact.json
      - ./attachments:/app/attachments
      - ./logs:/app/logs # Mount logs folder to host machine
      # Don't mount entire /app - that overwrites the built files!
    stdin_open: true
    tty: true
    shm_size: "2gb"